import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import QueryProvider from '../ui/QueryProvider';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='bg-slate-200 py-5'>
        <div className="container mx-auto">
          <div className="navigation flex gap-x-5 ">

            <Link href='/'>Home</Link>
            <Link href='/products'>Products</Link>
            <Link href='/products/add'>Add a Product</Link>
          </div>
        </div>
        </header>
       <main className='my-3'>
        <div className="container mx-auto">
          <QueryProvider>{children}</QueryProvider>
        </div>

       </main>
        
        </body>
    </html>
  )
}
