import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='bg-white py-5'>
        <div className="container mx-auto">
          <div className="navigation flex gap-x-5">

            <Link href='/'>Home</Link>
            <Link href='/about'>About</Link>
            <Link href='/blog'>Blog</Link>
            <Link href='/products'>Products</Link>
          </div>
        </div>
        </header>
       <main className='my-3'>
        <div className="container mx-auto">
          {children}
        </div>

       </main>
        
        </body>
    </html>
  )
}
